# Site settings
title: "hjhwang tech blog"
email: "hhjoong@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "https://hjhwang.github.io" # the subpath of your site, e.g. /blog/
url: "https://hjhwang.github.io" # the base hostname & protocol for your site

twitter_username: ""
facebook_username : "hyunjoong.hwang"
github_username: "hjhwang"

# Build settings
markdown: kramdown
